### ISSUE TITLE
Not working in landscape orientation

### ISSUE THREAD

**Issue by mychaelgo** [SiriDx/qrcode#2]
Camera crash while my Android in landscape. Not tested on iOS yet.

- Logs
```
I/CameraConfiguration(11983): Requesting focus mode value from among: [auto]
I/CameraConfiguration(11983): Supported focus mode values: [auto, infinity, macro, continuous-video, continuous-picture]
I/CameraConfiguration(11983): Can set focus mode to: auto
I/CameraConfiguration(11983): Focus mode already set to auto
I/CameraConfiguration(11983): Requesting flash mode value from among: [off]
I/CameraConfiguration(11983): Supported flash mode values: [off, auto, on, torch]
I/CameraConfiguration(11983): Can set flash mode to: off
I/CameraConfiguration(11983): Flash mode already set to off
I/PreviewScalingStrategy(11983): Viewfinder size: 0x0
I/PreviewScalingStrategy(11983): Preview in order of preference: [1920x1080, 1440x1080, 1088x1088, 1280x720, 1056x704, 1024x768, 960x720, 720x720, 720x480, 640x480, 352x288, 320x240, 256x144, 176x144]
I/CameraManager(11983): Final camera parameters: 3dnr=false;Infinity=Infinity;antibanding=50hz;antibanding-values=auto,50hz;auto-exposure-lock-supported=true;auto-whitebalance-lock-supported=true;best-capture=0;brightness=0;brightness-max=2;brightness-min=-2;burst-capture=0;burstshot-fps-values=(10,10);constant-growth-rate-zoom-supported=true;contrast=auto;drc=false;dual_mode=-1;dualrecording-hint=-1;dynamic-range-control=off;effect=none;effect-available-fps-values=(10000,24000);effect-values=none;effectrecording-hint=0;exif_exptime=0;exif_iso=0;exposure-compensation=0;exposure-compensation-step=0.1;exposure-time=0;fast-fps-mode=-1;flash-mode=off;flash-mode-values=off,auto,on,torch;fnumber-value-denominator=10;fnumber-value-numerator=19;focal-length=3.60;focallength-35mm-value=27;focallength-value-denominator=100;focallength-value-numerator=360;focus-areas=(0,0,0,0,0);focus-distances=0.10,1.20,Infinity;focus-mode=auto;focus-mode-values=auto,infinity,macro,continuous-video,continuous-picture;hdr-mode=0;horizontal-view-angle=64;hue=0;hue-max=2;hue-min=-2;imageuniqueid-value=0;intelligent-mode=-1;iso=auto;iso-values=auto,100,200,400,800;jpeg-quality=96;jpeg-thumbnail-height=384;jpeg-thumbnail-quality=100;jpeg-thumbnail-size-values=512x384,512x288,384x384,0x0;jpeg-thumbnail-width=512;max-exposure-compensation=20;max-num-detected-faces-hw=16;max-num-detected-faces-sw=0;max-num-focus-areas=1;max-num-metering-areas=0;max-zoom=30;maxaperture-value-denominator=100;maxaperture-value-numerator=185;metering=center;metering-areas=;metering-values=matrix,center,spot;min-exposure-compensation=-20;motion-speed=-1;odc=false;phase-af=on;phase-af-values=off,on;picture-format=jpeg;picture-format-values=jpeg;picture-size=4608x3456;picture-size-values=4608x3456,4608x2592,3456x3456,3264x2448,3264x1836,2448x2448,2048x1152,1920x1080,1280x720,960x720,640x480,320x240,256x144;preferred-preview-size-for-video=1920x1080;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p;preview-fps-range=15000,30000;preview-fps-range-values=(15000,15000),(24000,24000),(15000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30;preview-size-values=1920x1080,1440x1080,1088x1088,1280x720,1056x704,1024x768,960x720,720x720,720x480,640x480,352x288,320x240,256x144,176x144;rotation=0;rt-hdr=off;rt-hdr-values=off;saturation=0;saturation-max=2;saturation-min=-2;scene-mode=auto;scene-mode-values=auto;sharpness=0;sharpness-max=2;sharpness-min=-2;shot-mode=0;smooth-zoom-supported=false;vertical-view-angle=39;video-frame-format=nv21;video-size=1920x1080;video-size-values=1920x1080,1440x1080,1072x1072,1280x720,960x720,800x450,720x480,640x480,480x320,352x288,320x240,176x144;video-snapshot-supported=true;video-stabilization-supported=false;vrmode=-1;vrmode-supported=true;wb-k=0;wdr=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,daylight,cloudy-daylight;zoom=0;zoom-ratios=100,104,109,114,120,125,131,138,144,151,158,166,174,182,190,200,209,219,229,240,251,263,276,289,303,317,332,348,364,381,400;zoom-supported=true;preview-size=1920x1080
I/CenterCropStrategy(11983): Preview: 1920x1080; Scaled: 0x0; Want: 0x0
D/AndroidRuntime(11983): Shutting down VM
E/AndroidRuntime(11983): FATAL EXCEPTION: main
E/AndroidRuntime(11983): Process: com.adactive.walkstaff.dev, PID: 11983
E/AndroidRuntime(11983): java.lang.ArithmeticException: divide by zero
E/AndroidRuntime(11983):        at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(CameraPreview.java:389)
E/AndroidRuntime(11983):        at com.journeyapps.barcodescanner.CameraPreview.previewSized(CameraPreview.java:461)
E/AndroidRuntime(11983):        at com.journeyapps.barcodescanner.CameraPreview.access$300(CameraPreview.java:59)
E/AndroidRuntime(11983):        at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(CameraPreview.java:199)
E/AndroidRuntime(11983):        at android.os.Handler.dispatchMessage(Handler.java:101)
E/AndroidRuntime(11983):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(11983):        at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime(11983):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11983):        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(11983):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Lost connection to device.
```

**Comment by samuelcecilio** [comment]
On iOS the camera is inverted. On Android, it works on some devices, on others the screen goes black and the app crashes. I will test further and investigate details about which devices work...
